### ISSUE TITLE
Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause error

### ISSUE THREAD

**Issue by jacubero** [noironetworks/aci-integration-module#16]
Hello,I have followed the installation steps described in "https://github.com/group-policy/gbp-devstack" and "./stack.sh" stops with the following error:

 _sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1293, u'Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause') [SQL: u'\nCREATE TABLE aim_agents (\n\tid VARCHAR(36) NOT NULL, \n\tagent_type VARCHAR(255) NOT NULL, \n\thost VARCHAR(255) NOT NULL, \n\tbinary_file VARCHAR(255) NOT NULL, \n\tadmin_state_up BOOL NOT NULL, \n\tcreated_at TIMESTAMP NULL DEFAULT now(), \n\theartbeat_timestamp TIMESTAMP NULL DEFAULT now(), \n\tbeat_count INTEGER, \n\tdescription VARCHAR(255), \n\tversion VARCHAR(10), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uniq_agents0agent_type0host UNIQUE (agent_type, host), \n\tCHECK (admin_state_up IN (0, 1))\n)\n\n']

I think the problem is located in the create table in the upgrade() function in the following file:

"https://raw.githubusercontent.com/noironetworks/aci-integration-module/master/aim/db/migration/alembic_migrations/versions/accfe645090a_agent_resource.py"

Could you tell me how I can solve this problem?

**Comment by ivar-lazzaro** [comment]
AFAIK, GBP Shouldn't be installing aci-integration-module yet (it is still a prototype, not released).

**Comment by snaiksat** [comment]
Hi Jose, Sorry that you ran into this issue and had to spend time on it. Ideally, one should be using the in-tree devstack plugin installation to perform GBP installation. The instructions are here:
https://github.com/openstack/group-based-policy/blob/master/doc/source/installation.rst#using-devstack

Since you brought up this issue, I noticed that our wiki page has not been updated to point to the in-tree devstack plugin-based install. I have updated that wiki page.

Thanks,
Sumit.
